// Command genops compiles the vendored Stash SDL into genqlient operations and
// fragments, an operation manifest, and a machine-facing catalog. It runs as the
// first step of `go generate` (see generate.go), ahead of genqlient itself.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/lightning-rider-999/go-stashapp/internal/genops"
	"github.com/lightning-rider-999/go-stashapp/schema"
)

const header = "# Code generated by genops; DO NOT EDIT.\n\n"

func main() {
	schemaDir := flag.String("schema", "schema", "vendored SDL directory")
	overlayPath := flag.String("overlay", "operations/overlay.yaml", "curated overlay file")
	flag.Parse()

	if err := run(*schemaDir, *overlayPath); err != nil {
		fmt.Fprintln(os.Stderr, "genops:", err)
		os.Exit(1)
	}
}

func run(schemaDir, overlayPath string) error {
	c, err := genops.Compile(schemaDir, overlayPath, schema.SchemaVersion)
	if err != nil {
		return err
	}

	manifestJSON, err := c.Manifest.JSON()
	if err != nil {
		return err
	}
	catalogJSON, err := c.Catalog.JSON()
	if err != nil {
		return err
	}

	for _, w := range []struct {
		path    string
		content []byte
	}{
		{"operations/generated/fragments.graphql", []byte(header + c.Fragments)},
		{"operations/generated/operations.graphql", []byte(header + c.Operations)},
		{"operations/manifest.json", manifestJSON},
		{"schema/catalog.json", catalogJSON},
	} {
		if err := writeFile(w.path, w.content); err != nil {
			return err
		}
	}
	return nil
}

func writeFile(path string, b []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, b, 0o644)
}
