// Package stash is a Go client library for the Stash GraphQL API. It wraps the
// typed operations generated by genqlient with a configured transport, a typed
// error model, server-version compatibility checks, and a bounded fan-out
// helper for batch work.
//
// A [Client] is created with [NewClient] and configured through [Option]
// values or the STASHAPP_URL and STASHAPP_API_KEY environment variables. Pass
// [Client.GraphQL] to the generated operation functions:
//
//	c, err := stash.NewClient(stash.WithURL("http://stash.local:9999"))
//	resp, err := stash.Version(ctx, c.GraphQL())
package stash

import (
	"fmt"
	"log/slog"
	"net/http"
	"net/url"
	"os"
	"strings"
	"time"

	"github.com/Khan/genqlient/graphql"
)

// defaultTimeout bounds requests made through the default *http.Client. A
// caller-supplied client (via [WithHTTPClient]) keeps its own timeout instead.
const defaultTimeout = 30 * time.Second

// Client is a configured handle to a Stash GraphQL server. It carries the
// normalised endpoint, the HTTP transport that injects the ApiKey header, and a
// logger. It is safe for concurrent use; the underlying *http.Client is shared.
type Client struct {
	endpoint   string
	wsURL      string
	apiKey     string
	httpClient *http.Client
	gql        graphql.Client
	logger     *slog.Logger
}

// NewClient builds a [Client] from the given options and the environment.
//
// Configuration precedence for each setting is: an explicit option, then the
// environment variable (STASHAPP_URL, STASHAPP_API_KEY), then a default. The
// URL is required; if it resolves to empty, NewClient returns an error. The API
// key is optional, since some instances run unauthenticated.
//
// The URL is normalised to address the GraphQL endpoint (see [Client.Endpoint]).
// The ApiKey header is injected by wrapping the transport's RoundTripper, so a
// caller-supplied client from [WithHTTPClient] keeps its own timeout and
// settings while still authenticating.
func NewClient(opts ...Option) (*Client, error) {
	var cfg config
	for _, opt := range opts {
		opt(&cfg)
	}

	rawURL := cfg.rawURL
	if rawURL == "" {
		rawURL = os.Getenv("STASHAPP_URL")
	}
	if rawURL == "" {
		return nil, fmt.Errorf("stash: no URL configured (set STASHAPP_URL or use WithURL)")
	}

	endpoint, wsURL, err := normaliseURL(rawURL)
	if err != nil {
		return nil, err
	}

	apiKey := cfg.apiKey
	if !cfg.apiKeySet {
		apiKey = os.Getenv("STASHAPP_API_KEY")
	}

	httpClient := buildHTTPClient(cfg, apiKey)

	logger := cfg.logger
	if logger == nil {
		logger = slog.Default()
	}

	return &Client{
		endpoint:   endpoint,
		wsURL:      wsURL,
		apiKey:     apiKey,
		httpClient: httpClient,
		gql:        graphql.NewClient(endpoint, httpClient),
		logger:     logger,
	}, nil
}

// buildHTTPClient produces the *http.Client used for requests. A
// caller-supplied client keeps its own timeout and only has its transport
// wrapped to inject the key; otherwise a default client with a bounded timeout
// is created. The key is injected only when non-empty.
func buildHTTPClient(cfg config, apiKey string) *http.Client {
	if cfg.httpClient != nil {
		c := *cfg.httpClient
		c.Transport = apiKeyTransport(c.Transport, apiKey)
		return &c
	}

	timeout := cfg.timeout
	if timeout == 0 {
		timeout = defaultTimeout
	}
	return &http.Client{
		Timeout:   timeout,
		Transport: apiKeyTransport(http.DefaultTransport, apiKey),
	}
}

// apiKeyTransport wraps base with a RoundTripper that adds the ApiKey header.
// When key is empty the base transport is returned unwrapped, so no header is
// sent. A nil base falls back to http.DefaultTransport.
func apiKeyTransport(base http.RoundTripper, key string) http.RoundTripper {
	if key == "" {
		return base
	}
	if base == nil {
		base = http.DefaultTransport
	}
	return &authRoundTripper{base: base, apiKey: key}
}

// authRoundTripper injects the Stash ApiKey header on every request. It clones
// the request before mutating headers, as the [http.RoundTripper] contract
// requires.
type authRoundTripper struct {
	base   http.RoundTripper
	apiKey string
}

// RoundTrip adds the ApiKey header to a clone of req and delegates to the base
// transport.
func (t *authRoundTripper) RoundTrip(req *http.Request) (*http.Response, error) {
	clone := req.Clone(req.Context())
	clone.Header.Set("ApiKey", t.apiKey)
	return t.base.RoundTrip(clone)
}

// normaliseURL parses rawURL and returns the GraphQL endpoint and the matching
// WebSocket URL. A bare host or a root path gains a /graphql suffix; a path that
// already ends in /graphql is kept. The WebSocket URL maps http to ws and https
// to wss while preserving host and path. A URL without a scheme or host is
// rejected.
func normaliseURL(rawURL string) (endpoint, wsURL string, err error) {
	u, err := url.Parse(rawURL)
	if err != nil {
		return "", "", fmt.Errorf("stash: parsing URL %q: %w", rawURL, err)
	}
	if u.Scheme == "" || u.Host == "" {
		return "", "", fmt.Errorf("stash: URL %q must include a scheme and host (e.g. http://host:port)", rawURL)
	}

	path := strings.TrimRight(u.Path, "/")
	switch {
	case path == "":
		path = "/graphql"
	case strings.HasSuffix(path, "/graphql"):
		// Already targets the endpoint; leave it.
	default:
		path += "/graphql"
	}
	u.Path = path

	wsScheme := u.Scheme
	switch u.Scheme {
	case "http":
		wsScheme = "ws"
	case "https":
		wsScheme = "wss"
	}
	ws := *u
	ws.Scheme = wsScheme

	return u.String(), ws.String(), nil
}

// GraphQL returns the genqlient client to pass to generated operation
// functions, for example stash.Version(ctx, c.GraphQL()).
func (c *Client) GraphQL() graphql.Client { return c.gql }

// Endpoint returns the normalised GraphQL endpoint, of the form
// http(s)://host[:port]/path/graphql.
func (c *Client) Endpoint() string { return c.endpoint }

// WebSocketURL returns the subscription endpoint derived from the configured
// URL, with the scheme mapped from http to ws and https to wss and the path
// preserved.
func (c *Client) WebSocketURL() string { return c.wsURL }

// HTTPClient returns the underlying *http.Client, whose transport injects the
// ApiKey header. The upload island reuses it so multipart requests carry the
// same authentication.
func (c *Client) HTTPClient() *http.Client { return c.httpClient }

// APIKey returns the configured API key. The WebSocket subprotocol handshake
// needs it directly because authentication there is carried in the connection
// init payload rather than an HTTP header.
func (c *Client) APIKey() string { return c.apiKey }

// Logger returns the diagnostics logger. It is never nil; an unconfigured
// client uses slog.Default.
func (c *Client) Logger() *slog.Logger { return c.logger }

// LogValue implements [slog.LogValuer] so a Client can be logged as a structured
// value with its API key redacted. The key is never written to logs.
func (c *Client) LogValue() slog.Value {
	attrs := []slog.Attr{
		slog.String("endpoint", c.endpoint),
	}
	if c.apiKey != "" {
		attrs = append(attrs, slog.String("api_key", "REDACTED"))
	}
	return slog.GroupValue(attrs...)
}
