package conformance

import (
	"bytes"
	"os"
	"strconv"
	"testing"

	"github.com/lightning-rider-999/go-stashapp/schema"
	genops "github.com/trackness/graphql-opgen"
)

// genHeader is the verbatim banner the genops generator (cmd/genops) prepends to
// the generated .graphql artefacts before writing them to disk. Compile() returns
// the body without it, so the committed-file comparison must add it back.
const genHeader = "# Code generated by genops; DO NOT EDIT.\n\n"

// Committed generated artefacts, relative to this package (internal/conformance).
// These are the exact paths cmd/genops/main.go writes; the byte-for-byte gate
// below pins each one to a fresh Compile() so `go test` fails on a stale or
// hand-edited artefact (catching what the Taskfile's git-diff step would, but
// inside the test binary).
const (
	committedFragmentsPath  = "../../internal/gen/generated/fragments.graphql"
	committedOperationsPath = "../../internal/gen/generated/operations.graphql"
	committedManifestPath   = "../../internal/gen/generated/manifest.json"
	committedCatalogPath    = "../../schema/catalog.json"
	committedCLICatalogPath = "../../cmd/stash/catalog.json"
)

// TestDeterminism is gate 12: compiling the surface twice must yield
// byte-identical artefacts. Fragments, operations, the manifest JSON, and the
// catalog JSON are all checked into the repo; if generation were non-deterministic
// (map iteration order leaking into output, say), the committed files would churn
// and the freshness gate in `task check` would become a coin flip. This pins
// determinism at the source.
func TestDeterminism(t *testing.T) {
	cfg := stashConfig()
	first, err := genops.Compile(schemaDir, overlayPath, schema.SchemaVersion, cfg)
	if err != nil {
		t.Fatalf("first compile: %v", err)
	}
	second, err := genops.Compile(schemaDir, overlayPath, schema.SchemaVersion, cfg)
	if err != nil {
		t.Fatalf("second compile: %v", err)
	}

	if first.Fragments != second.Fragments {
		t.Error("Fragments differ between two compiles")
	}
	if first.Operations != second.Operations {
		t.Error("Operations differ between two compiles")
	}

	firstManifestB, err := first.Manifest.JSON()
	if err != nil {
		t.Fatalf("first manifest JSON: %v", err)
	}
	secondManifestB, err := second.Manifest.JSON()
	if err != nil {
		t.Fatalf("second manifest JSON: %v", err)
	}
	if !bytes.Equal(firstManifestB, secondManifestB) {
		t.Error("Manifest JSON differs between two compiles")
	}

	firstCatalogB, err := first.Catalog.JSON()
	if err != nil {
		t.Fatalf("first catalog JSON: %v", err)
	}
	secondCatalogB, err := second.Catalog.JSON()
	if err != nil {
		t.Fatalf("second catalog JSON: %v", err)
	}
	if !bytes.Equal(firstCatalogB, secondCatalogB) {
		t.Error("Catalog JSON differs between two compiles")
	}
}

// TestCommittedArtefactsAreFresh is gate 12b: a fresh genops.Compile() must
// reproduce the committed generated artefacts byte-for-byte. determinism (above)
// proves a compile is reproducible in-process, but says nothing about whether the
// files checked into the repo actually match the current schema + overlay. This
// reads each committed file from disk and diffs it against Compile(), so a stale
// artefact (someone changed the SDL/overlay but forgot `task generate`) or a
// hand-edited one turns `go test` red — not only the Taskfile's git-diff step,
// which a contributor running plain `go test` would never trigger.
//
// The five committed artefacts cmd/genops writes are all covered:
//
//	internal/gen/generated/fragments.graphql   (genHeader + Compiled.Fragments)
//	internal/gen/generated/operations.graphql  (genHeader + Compiled.Operations)
//	internal/gen/generated/manifest.json                 (Manifest.JSON)
//	schema/catalog.json                      (Catalog.JSON)
//	cmd/stash/catalog.json                   (same Catalog.JSON, embedded by the CLI)
func TestCommittedArtefactsAreFresh(t *testing.T) {
	c, err := genops.Compile(schemaDir, overlayPath, schema.SchemaVersion, stashConfig())
	if err != nil {
		t.Fatalf("compile: %v", err)
	}

	manifestJSON, err := c.Manifest.JSON()
	if err != nil {
		t.Fatalf("manifest JSON: %v", err)
	}
	catalogJSON, err := c.Catalog.JSON()
	if err != nil {
		t.Fatalf("catalog JSON: %v", err)
	}

	cases := []struct {
		path string
		want []byte
	}{
		{committedFragmentsPath, []byte(genHeader + c.Fragments)},
		{committedOperationsPath, []byte(genHeader + c.Operations)},
		{committedManifestPath, manifestJSON},
		{committedCatalogPath, catalogJSON},
		// cmd/stash/catalog.json is a byte-identical copy of schema/catalog.json
		// (the CLI embeds it); compiling once and diffing both pins that too.
		{committedCLICatalogPath, catalogJSON},
	}

	for _, tc := range cases {
		got, err := os.ReadFile(tc.path)
		if err != nil {
			t.Errorf("reading committed artefact %s: %v", tc.path, err)
			continue
		}
		if !bytes.Equal(got, tc.want) {
			t.Errorf("committed artefact %s is stale or hand-edited: it does not match a fresh genops.Compile().\n"+
				"  committed: %d bytes\n  generated: %d bytes\n%s\n"+
				"Run `task generate` to regenerate it from the current schema + overlay.",
				tc.path, len(got), len(tc.want), firstDiff(got, tc.want))
		}
	}
}

// firstDiff returns a short, human-readable description of the first byte where
// a and b differ, with a little surrounding context, so a stale-artefact failure
// points at the divergence instead of dumping two large files.
func firstDiff(a, b []byte) string {
	n := min(len(a), len(b))
	for i := 0; i < n; i++ {
		if a[i] != b[i] {
			return "  first difference at byte " + strconv.Itoa(i) + ":\n" +
				"    committed: " + quoteWindow(a, i) + "\n" +
				"    generated: " + quoteWindow(b, i)
		}
	}
	if len(a) != len(b) {
		return "  one file is a prefix of the other (length differs); the shorter is truncated"
	}
	return ""
}

// quoteWindow renders up to 40 bytes of s starting at i as a quoted Go string,
// for diff context.
func quoteWindow(s []byte, i int) string {
	end := min(i+40, len(s))
	return strconv.Quote(string(s[i:end]))
}
